---
- name: Atualiza o cache apt de nosso servidor
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  
- name: Instala os pacotes necessarios
  apt: name={{ item }} state=present
  with_items:
  - apache2
  - mysql-server
  - php-mysql
  - php
  - libapache2-mod-php
  - python3-mysqldb
# tasks file for server
